"""add_concept_and_dream_tables

Revision ID: 68b15f3612bb
Revises: 
Create Date: 2025-08-02 21:15:17.751069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68b15f3612bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dreams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dreams_created_at_desc', 'dreams', ['created_at'], unique=False)
    op.create_index(op.f('ix_dreams_id'), 'dreams', ['id'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parent1_id', sa.String(length=36), nullable=True),
    sa.Column('parent2_id', sa.String(length=36), nullable=True),
    sa.Column('dream_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent1_id'], ['concepts.id'], ),
    sa.ForeignKeyConstraint(['parent2_id'], ['concepts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepts_dream_id'), 'concepts', ['dream_id'], unique=False)
    op.create_index(op.f('ix_concepts_id'), 'concepts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepts_id'), table_name='concepts')
    op.drop_index(op.f('ix_concepts_dream_id'), table_name='concepts')
    op.drop_table('concepts')
    op.drop_index(op.f('ix_dreams_id'), table_name='dreams')
    op.drop_index('ix_dreams_created_at_desc', table_name='dreams')
    op.drop_table('dreams')
    # ### end Alembic commands ###
